default: &default
  adapter: postgresql
  port: 5432
  username: postgres
  password: password
  host: 127.0.0.1
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: elasticsearch_rails_sandbox_development

test:
  <<: *default
  database: elasticsearch_rails_sandbox_test

production:
  <<: *default
  database: elasticsearch_rails_sandbox_production
  username: elasticsearch_rails_sandbox
  password: <%= ENV['ELASTICSEARCH_RAILS_SANDBOX_DATABASE_PASSWORD'] %>
